import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import '../globals.css';
import styles from './layout.module.css';
import { Header } from './header/header';
import { Sidebar } from './sidebar/sidebar';
import { Footer } from './footer/footer';

const noto_sans_font = Noto_Sans({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={noto_sans_font.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar} />
          <div className={styles.main}>{children}</div>
          <Footer className={styles.footer} />
        </div>
      </body>
    </html>
  );
}
