import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

const noto_sans_font = Noto_Sans({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={noto_sans_font.className}>{children}</body>
    </html>
  );
}
